services:
  next:
    image: ghcr.io/plumpqueen/devopsrepo/nodejs-my-website:latest
    restart: always
    networks:
      - reverse-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.next-production.rule=PathPrefix(`/next`)"
      - "traefik.http.routers.next-production.entrypoints=web"
      #- "traefik.http.middlewares.test-stripprefix.stripprefix.prefixes=/next"
      #- "traefik.http.routers.next-production.middleware=test-stripprefix"

  adminer:
    image: adminer
    #restart: always
    networks:
      - reverse-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer-production.rule=PathPrefix(`/adminer`)"
      - "traefik.http.routers.adminer-production.entrypoints=web"

  db:
    image: mariadb:10.6
    environment:
      MARIADB_DATABASE: cube
      MARIADB_USER: cube
      MARIADB_PASSWORD: cube
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./docker/db/data:/var/lib/mysql

  #watchtower:
  #  image: containrrr/watchtower
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #  command: ghcr.io/plumpqueen/devopsrepo/nodejs-my-website:latest --interval=30 #watchtower va check toutes les 30sec s'il y a une màj


networks: # recherche du network créé dans docker-compose.global
  reverse-proxy:
    name: reverse-proxy
    driver: bridge