services:
  next:
    image: ghcr.io/plumpqueen/devopsrepo/nodejs-my-website:developpement
    restart: always
    ports:
      - 3001:3000

  adminer:
    image: adminer
    ports:
      - 8081:8080

  db:
    image: mariadb:10.6
    environment:
      MARIADB_DATABASE: cube
      MARIADB_USER: cube
      MARIADB_PASSWORD: cube
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./docker/db/data:/var/lib/mysql
