services:
  next:
    image: ghcr.io/plumpqueen/devopsrepo/nodejs-my-website:latest
    restart: always
    ports:
      - 3000:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=PathPrefix(`whoami.localhost`)" #PathPrefix = règle voir doc router traefik
      - "traefik.http.routers.whoami.entrypoints=web"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db:
    image: mariadb:10.6
    environment:
      MARIADB_DATABASE: cube
      MARIADB_USER: cube
      MARIADB_PASSWORD: cube
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./docker/db/data:/var/lib/mysql

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ghcr.io/plumpqueen/devopsrepo/nodejs-my-website:latest --interval=30 #watchtower va check toutes les 30sec s'il y a une màj


networks: # recherche du network créé dans docker-compose.global
  reverse-proxy:
    name: reverse-proxy
    driver: bridge