name: test workflow du projet
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #CACHE
      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: |
          node_modules
          /home/runner/.cache/Cypress
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        name: Install Depedencies and build
          - run: npm install
          - run: npm run build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
          node_modules
          /home/runner/.cache/Cypress
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - run: npm run e2e:headless
      #ARTIFACT
      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: e2e-tests
          path: cypress/videos

    # SAVE CACHE

